Repository spencerwooo/onedrive-vercel-index, pull requests merged in 2021-12, with the labels that each got.

#186 fix(pdfpreview): Support for non-latin characters
  components/previews/PDFPreview.tsx
Labels: bug

#169 Selecting to download support for current directory
  components/FileListing.tsx
  components/Navbar.tsx
  package-lock.json
  package.json
  pages/[...path].tsx
  pages/index.tsx
  utils/tools.ts
Labels: enhancement

#177 Folder download
  components/FileListing.tsx
  components/Loading.tsx
  utils/tools.ts
Labels: enhancement

#202 Native PDF preview, proxied download, better buttons, download button sticky
  components/Auth.tsx
  components/DownloadBtn.tsx
  components/DownloadBtnGtoup.tsx
  components/FileListing.tsx
  components/FourOhFour.tsx
  components/Navbar.tsx
  components/previews/AudioPreview.tsx
  components/previews/CodePreview.tsx
  components/previews/EPUBPreview.tsx
  components/previews/MarkdownPreview.tsx
  components/previews/OfficePreview.tsx
  components/previews/PDFPreview.tsx
  components/previews/TextPreview.tsx
  components/previews/VideoPreview.tsx
  config/site.json
  package-lock.json
  package.json
  pages/_app.tsx
  styles/globals.css
  tailwind.config.js
Labels: enhancement

#206 Proxied download documentations
  README.md
Labels: documentation

#210 OAuth inside main project with public client ID and secret
  README.md
  components/Auth.tsx
  components/FileListing.tsx
  components/FourOhFour.tsx
  config/api.json
  config/site.json
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/index.ts
  pages/onedrive-vercel-index-oauth/step-1.tsx
  pages/onedrive-vercel-index-oauth/step-2.tsx
  pages/onedrive-vercel-index-oauth/step-3.tsx
  public/images/empty.png
  public/images/fabulous-celebration.png
  public/images/fabulous-come-back-later.png
  public/images/fabulous-fireworks.png
  public/images/fabulous-page-not-found.png
  public/images/fabulous-rip-2.png
  public/images/fabulous-wapmire-weekdays.png
  public/images/no-looking.png
  public/images/step-2-screenshot.png
  tailwind.config.js
  utils/oAuthHandler.ts
  utils/odAuthTokenStore.ts
Labels: enhancement
