Repository spencerwooo/onedrive-vercel-index, pull requests merged in 2022-01, with the labels that each got.

#236 Flat design with custom file preview hook
  components/Auth.tsx
  components/Breadcrumb.tsx
  components/FileListing.tsx
  components/Footer.tsx
  components/FourOhFour.tsx
  components/Loading.tsx
  components/Navbar.tsx
  components/previews/AudioPreview.tsx
  components/previews/CodePreview.tsx
  components/previews/Containers.tsx
  components/previews/EPUBPreview.tsx
  components/previews/MarkdownPreview.tsx
  components/previews/OfficePreview.tsx
  components/previews/PDFPreview.tsx
  components/previews/TextPreview.tsx
  components/previews/VideoPreview.tsx
  package-lock.json
  styles/globals.css
  tailwind.config.js
  utils/fetchOnMount.ts
  utils/fetchWithSWR.ts
Labels: enhancement

#303 Search support for OneDrive Business
  components/SearchModal.tsx
  components/previews/CodePreview.tsx
  components/previews/MarkdownPreview.tsx
  components/previews/TextPreview.tsx
  components/previews/URLPreview.tsx
  pages/api/index.ts
  pages/api/item.ts
  pages/api/search.ts
  types/index.d.ts
  utils/fetchOnMount.ts
Labels: bug

#308 Clean path param earlier
  pages/api/index.ts
Labels: bug

#231 Error handling in traversing
  components/FileListing.tsx
  components/MultiFileDownloader.tsx
Labels: feature request

#304 Differ file types which have the same extensions
  components/FileListing.tsx
  components/previews/DefaultPreview.tsx
  pages/api/index.ts
  types/index.d.ts
  utils/getFileIcon.ts
  utils/getPreviewType.ts
Labels: feature request

#306 Support custom url final component name for Notion
  pages/api/name/[name].ts
Labels: feature request

#315 Add CORS for raw file link
  package-lock.json
  package.json
  pages/api/index.ts
Labels: feature request
